[core]
base_currency = "USD"
mode = "paper"  # paper only in v0.2
data_dir = "./data"
log_level = "INFO"

[exchanges.kraken]
api_key = "env:KRAKEN_KEY"
api_secret = "env:KRAKEN_SECRET"
sandbox = true  # paper mode

[llm]
provider = "openai"  # openai|azure|openrouter|local
model = "gpt-4o-mini"
max_tokens = 1000
temperature = 0.1
hourly_token_budget = 50000
daily_token_budget = 500000
planning_enabled = true
planning_interval_seconds = 300  # 5 minutes
use_cache = true
cache_ttl_minutes = 15

# Provider-specific configurations
[llm.providers.openai]
api_key = "env:OPENAI_API_KEY"
base_url = "https://api.openai.com/v1"
model = "gpt-4o-mini"
hourly_token_budget = 50000
daily_token_budget = 500000

[llm.providers.azure]
api_key = "env:AZURE_OPENAI_KEY"
endpoint = "env:AZURE_OPENAI_ENDPOINT"
model = "gpt-4o-mini"
api_version = "2024-02-15-preview"
hourly_token_budget = 50000
daily_token_budget = 500000

[llm.providers.openrouter]
api_key = "env:OPENROUTER_API_KEY"
base_url = "https://openrouter.ai/api/v1"
model = "meta-llama/llama-3.1-8b-instruct:free"
hourly_token_budget = 100000  # Higher limit for cheaper models
daily_token_budget = 1000000

[llm.providers.local]
base_url = "http://localhost:11434"  # Ollama default
model = "llama3.1:8b"
hourly_token_budget = 1000000  # No real limit for local models
daily_token_budget = 10000000

[memory]
max_context_tokens = 128000            # provider limit
target_window_tokens = 24000           # planner budget
rag_top_k = 6                          # retrieved snippets
summarize_every_events = 25            # episodic summary cadence
summarize_every_minutes = 15           # time-based fallback
summary_target_tokens = 1200           # per summary
use_local_summarizer = true            # Ollama/llama.cpp

[risk]
max_position_pct = 0.25
daily_loss_limit_pct = 2.0
max_orders_per_hour = 6
circuit_breaker_spread_bps = 50

[ui]
port = 5173
api_port = 8080
show_thinking_feed = true
theme = "ocean"

[database]
url = "sqlite:///./data/wave.db"
echo = false  # SQL logging

[strategies]
default_symbols = ["BTC/USDT", "ETH/USDT"]
default_timeframe = "5m"
max_active_strategies = 5

# M3 Advanced Configuration

[optimization]
enabled = true
genetic_algorithm_generations = 100
genetic_algorithm_population = 50
bayesian_optimization_iterations = 200
parallel_optimization_workers = 4
cache_optimization_results = true

[portfolio]
max_strategies = 20
rebalancing_frequency = "weekly"
risk_parity_enabled = true
correlation_limit = 0.7
drawdown_rebalance_threshold = 0.05
max_single_strategy_weight = 0.4
min_strategy_weight = 0.01
rebalance_deviation_threshold = 0.05

[reporting]
generate_daily_reports = true
generate_monthly_reports = true
export_formats = ["pdf", "csv", "json"]
report_retention_days = 365
scheduled_reports_enabled = true
performance_benchmark = "market"

[live_trading]
enabled = false  # Still evaluation phase
max_position_value = 1000.0  # USD
emergency_stop_drawdown = 0.10
pre_trade_checks_timeout = 1000  # ms
position_monitoring_frequency = 1  # seconds
slippage_tolerance_bps = 10

[performance]
calculate_advanced_metrics = true
regime_detection_enabled = true
stress_testing_enabled = true
monte_carlo_simulations = 1000
walk_forward_enabled = true
walk_forward_window_months = 12
walk_forward_step_months = 1

[backtesting]
default_lookback_days = 365
enable_walk_forward = true
enable_monte_carlo = true
enable_stress_testing = true
max_concurrent_backtests = 4

[analytics]
performance_cache_ttl_minutes = 60
regime_detection_lookback_days = 252
correlation_analysis_enabled = true
attribution_analysis_enabled = true